image: node:22

stages:
  - format
  - build

variables:
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
  RUSTUP_HOME: "$CI_PROJECT_DIR/.rustup"

build-n-lint-job:
  stage: build
  rules:
    - if: $CI_COMMIT_TITLE =~ /-draft$/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "Building Tauri app..."
    - apt-get update && apt-get install -y libwebkit2gtk-4.1-dev libssl-dev libappindicator3-dev librsvg2-dev patchelf curl xdg-utils
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - export PATH="$CARGO_HOME/bin:$PATH"
    - rustup show
    - echo "Versions:"
    - node -v
    - rustc -V
    - rustup -V
    - npm ci --cache .npm --prefer-offline
    - npm run tauri build
  # artifacts:
  #   paths:
  #     - src-tauri/target/release/bundle/tauri-app.exe
  #   expire_in: 1 day
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - dist/
      - src-tauri/target/
      - .cargo/
      - .rustup/
      - .npm/
    policy: pull-push

format-job:
  stage: format
  rules:
    - when: always # Very light job
  script:
    - echo "Checking Prettier formatting..."
    - pwd
    - npx prettier . --check
